baseURL = "https://example.com"
title = "luocang-blog"
theme = "m10c"
paginate = 5

[menu]
[[menu.main]]
    identifier = "ubuntu"
    name       = "ubuntu系统搭建"
    url        = "/tags/ubuntu"

[[menu.main]]
    identifier = "Hi3559a"
    name       = "Hi3559a开发"
    url        = "/tags/Hi3559a"

[[menu.main]]
    identifier = "lichee"
    name       = "lichee学习"
    url        = "/tags/lichee"

[[menu.main]]
    identifier = "shuixia"
    name       = "shuixia工作"
    url        = "/tags/shuixia"

[params]
    author = "John Doe"
    description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula turpis sit amet elit pretium."
    menu_item_separator = "-------------(cang)"
[[params.social]]
    name = "github"
    url = "https://github.com/shuishen-cang"

[[params.social]]
    name = "gitee"
    url = "https://gitee.com/shuishen-cang/"

[markup.goldmark.renderer]
    unsafe= true