baseURL = "https://shuishen-cang.github.io/"
languageCode = "en-us"
title = "洛沧"
theme = "m10c2"

[[menu.main]]
    identifier = "blog"
    name       = "Blogs"
    url        = "/post"

[[params.social]]
    name = "github"
    url = "https://github.com/shuishen-cang"

[[params.social]]
    name = "gitee"
    url = "https://gitee.com/shuishen-cang/"

[params.style]
    # darkestColor = "#d35050"
    # darkColor = "#212121"
    # lightColor = "#f5e3e0"
    # lightestColor = "#f5f5f5"
    # primaryColor = "#fff"